<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Mahesh" failures="1" tests="1" name="grouping(failed)" time="24.441" errors="0" timestamp="2025-10-06T11:00:28 IST">
  <testcase classname="testcases.TC_002_LoginTest" name="verify_Login" time="13.684">
    <failure type="java.lang.AssertionError" message="Login Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login Failed expected [true] but found [false]
at testcases.TC_002_LoginTest.verify_Login(TC_002_LoginTest.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- verify_Login -->
</testsuite> <!-- grouping(failed) -->
